spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 8918919b3bad8fcab8e0
            client-secret: 08cec283241cded9ff5a9b428afe116dfe8429e5

#logging:
#  level:
#    org.springframework.security: DEBUG
